### ISSUE TITLE
Loading pre-trained StyleGan2 pickle from original implementation

### ISSUE THREAD

**Issue by nzohrab** [rosasalberto/StyleGAN2-TensorFlow-2.x#2]
I notice you are loading pre-trained networks from .npy files, rather than from .pkl files. May I ask how you converted the pre-trained models from .pkl to .npy, assuming you did not re-train from scratch.

**Comment by nzohrab** [comment]
I have updated weights_map.py as necessary to load my own model (updated available_weights, synthesis_weights, and discriminator_weights). I have also moved my .pkl file to weights/.
Running the generator outputs:
`
Traceback (most recent call last):
  File "s.py", line 39, in <module>
    generator = StyleGan2Generator(weights=weights_name, impl=impl, gpu=gpu)
  File "/home/nicky/Downloads/StyleGAN2-TensorFlow-2.x-master/stylegan2_generator.py", line 151, in __init__
    self.__load_weights(weights)
  File "/home/nicky/Downloads/StyleGAN2-TensorFlow-2.x-master/stylegan2_generator.py", line 204, in __load_weights
    data = np.load(weights_stylegan2_dir + weights_name + '.pkl', allow_pickle=True)[()]
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 449, in load
    raise IOError(
OSError: Failed to interpret file 'weights/my_model.pkl' as a pickle
`

**Comment by rosasalberto** [comment]
I think your question is how I obtained the weights from the Nvidia pickle files.
For doing that, you have to download their repository, load the desired model and, get the value of the graph variables.
An example on how to obtain discriminator ffhq weights would be:

```
data = {}
name = 'ffhq'
g, d, Gs_network = pretrained_networks.load_networks('models/model_styleGAN2/stylegan2-{}-config-f.pkl'.format(name))
for key in  d.trainables.keys():
        data['disc_'+ key] = d.get_var(key)
```
